### ISSUE TITLE
This repository is over its data quota. 

### ISSUE THREAD

**Issue by qihao-huang** [ElementAI/synbols-resources#5]
[https://github.com/fgolemo/cl-workshop-cvpr21-docker/issues/15](url)

```
git lfs clone https://github.com/ElementAI/synbols-resources.git
WARNING: 'git lfs clone' is deprecated and will not be updated
          with new flags from 'git clone'

'git clone' has been updated in upstream Git to have comparable
speeds to 'git lfs clone'.
Cloning into 'synbols-resources'...
remote: Enumerating objects: 10052, done.
remote: Counting objects: 100% (28/28), done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 10052 (delta 4), reused 19 (delta 3), pack-reused 10024
Receiving objects: 100% (10052/10052), 293.88 MiB | 1.54 MiB/s, done.
Resolving deltas: 100% (1834/1834), done.
Updating files: 100% (9124/9124), done.
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/ElementAI/synbols-resources.git/info/lfs'
```

**Comment by aldro61** [comment]
Thanks for reporting this issue. It seems like we exceeded the bandwidth quotas for the month (too many downloads). We are looking into a quick fix.

**Comment by aldro61** [comment]
We are in the process of moving the datasets to Zenodo. We will adapt the loader in "synbols-benchmarks" to load data from there instead.

**Comment by aldro61** [comment]
The data has been released to https://zenodo.org/record/4701316. @prlz77 will now update the data loader in https://github.com/ElementAI/synbols-benchmarks. Then everything should be fixed.

**Comment by aldro61** [comment]
@prlz77's new loader works. It now includes two mirrors for the data: 1) zenodo, 2) github. https://github.com/ElementAI/synbols-benchmarks/commit/f9134fef7f35d325c0114a4ba832a027b92e2fc5.

Marking this issue as resolved.
